export const metadata = {
  title: 'Next.js OAuth',
  description: 'Generated by user cum Next.JS combo',
}

export default function RoutingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#121212', color: '#e0e0e0', margin: 0 }}>
        {/* Render children (main content) */}
        <div style={{ paddingTop: '60px', paddingBottom: '60px', display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center"}}>
          {children}
        </div>

        <footer style={{
          position: 'fixed',
          bottom: '0',
          left: '0',
          right: '0',
          backgroundColor: 'rgba(255, 255, 255, 0.1)',  // Semi-transparent white for glass effect
          backdropFilter: 'blur(10px)',  // Applies the glassmorphism effect
          borderTopLeftRadius: '20px',
          borderTopRightRadius: '20px',
          padding: '10px 20px',
          textAlign: 'center',  // Centers the content inside the footer
          zIndex: '1000',  // Ensures the footer stays on top of other content
          color: '#e0e0e0',  // Light text for contrast
          boxShadow: '0 -4px 6px rgba(0, 0, 0, 0.1)', // Subtle shadow to give depth
        }}>
          Footer
        </footer>
      </body>
    </html>
  )
}
